import { Context, Effect, Layer } from "effect"
import { WasmLoadError } from "./errors"

// ---------------------------------------------------------------------------
// WasmModule interface
// ---------------------------------------------------------------------------

export interface WasmModule {
  readonly keygen: (seed: Uint8Array) => { sk: Uint8Array; vk: Uint8Array }
  readonly sign: (
    skBytes: Uint8Array,
    message: Uint8Array,
    salt: Uint8Array,
  ) => {
    signature: Uint8Array
    salt: Uint8Array
  }
  readonly verify: (
    vkBytes: Uint8Array,
    message: Uint8Array,
    signature: Uint8Array,
  ) => boolean
  readonly create_verification_hint: (
    s1: Int32Array,
    pkNtt: Int32Array,
  ) => Uint16Array
  readonly pack_public_key_wasm: (pkNtt: Uint16Array) => string[]
  readonly public_key_length: () => number
  readonly salt_length: () => number
}

// ---------------------------------------------------------------------------
// Runtime type validation — no `as any` or `as unknown as WasmModule`
// ---------------------------------------------------------------------------

/**
 * Runtime guard that checks every method in the WasmModule interface exists
 * and is a function. Returns true only when all seven methods are present.
 *
 * This replaces the unsafe `as unknown as WasmModule` cast that was used in
 * the original implementation.
 *
 * Validation scope: checks that each required key is present and is a
 * function. Function arity and return types cannot be checked without
 * invoking the function (which would have side effects), so only presence
 * and kind are validated here.
 *
 * No type assertions are used: after the null/typeof guard, TypeScript
 * narrows `mod` to `object`, which satisfies `Reflect.get`'s `target:
 * object` parameter — property access is type-safe without any cast.
 */
export function isValidWasmModule(mod: unknown): mod is WasmModule {
  if (mod === null || typeof mod !== "object") return false
  // TypeScript narrows `mod` to `object` here — no type assertion needed.
  // Reflect.get accepts `object` as its first argument directly.
  const methods = [
    "keygen",
    "sign",
    "verify",
    "create_verification_hint",
    "pack_public_key_wasm",
    "public_key_length",
    "salt_length",
  ] as const
  return methods.every((method) => typeof Reflect.get(mod, method) === "function")
}

// ---------------------------------------------------------------------------
// Context.Tag — WasmRuntime service tag
// ---------------------------------------------------------------------------

export class WasmRuntime extends Context.Tag("WasmRuntime")<
  WasmRuntime,
  WasmModule
>() {}

// ---------------------------------------------------------------------------
// Internal load function — uses Effect.fn for automatic span tracing
// ---------------------------------------------------------------------------

const loadWasmModule = Effect.fn("WasmRuntime.load")(function* () {
  const mod = yield* Effect.tryPromise({
    try: async () => {
      // Dynamic import of the WASM JS glue generated by wasm-pack.
      // The `/* webpackIgnore: true */` comment prevents bundlers from
      // trying to resolve this path at build time.
      const modulePath = "/wasm/falcon_rs.js"
      const imported = await import(
        /* webpackIgnore: true */
        modulePath
      )
      // Run the WASM initializer (wasm-pack generates a default export
      // that downloads and instantiates the .wasm binary).
      await imported.default()
      return imported
    },
    catch: (error) =>
      new WasmLoadError({
        message: `Failed to load WASM module: ${String(error)}`,
      }),
  })

  // Runtime validation — replaces unsafe `as unknown as WasmModule`
  if (!isValidWasmModule(mod)) {
    return yield* Effect.fail(
      new WasmLoadError({
        message:
          "WASM module is missing required methods. Expected: keygen, sign, verify, " +
          "create_verification_hint, pack_public_key_wasm, public_key_length, salt_length.",
      }),
    )
  }

  yield* Effect.log("WasmRuntime loaded successfully")
  return mod
})

// ---------------------------------------------------------------------------
// WasmRuntimeLive — Layer that loads and validates the WASM module
//
// Effect's Layer memoization guarantees this effect runs at most once when
// the Layer is provided to the application. There is no mutable global state
// (`let cachedModule`); the singleton guarantee comes from Layer itself.
// ---------------------------------------------------------------------------

export const WasmRuntimeLive = Layer.effect(WasmRuntime, loadWasmModule())
